/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 ../../../public/models/soczewiak.glb --transform 
Files: ../../../public/models/soczewiak.glb [66.53KB] > soczewiak-transformed.glb [5.48KB] (92%)
*/

import { useState } from 'react'
import { useGLTF, Edges } from '@react-three/drei'

export function Soczewiak({ handleClick }) {
  const { nodes, materials } = useGLTF('/models/soczewiak-transformed.glb')
  const [isHovered, setIsHovered] = useState(false)

  return (
    <group dispose={null}>
      <mesh 
        geometry={nodes.Plane.geometry} 
        material={materials['Material.001']} 
        position={[-0.024, 0, -0.039]} 
        rotation={[1.2, 0, 0]}
        scale={0.6} 
        onPointerEnter={()=>setIsHovered(true)}
			  onPointerLeave={()=>setIsHovered(false)}
        onClick={handleClick}
      >
        {isHovered ? <Edges scale={1} threshold={0} color="black" /> : null }
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/soczewiak-transformed.glb')
